add ekner

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,44 +5,45 @@ on:
     branches: ['main']
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
+  #   build:
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #       - uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 23.x
+  #       - name: Set up Node.js
+  #         uses: actions/setup-node@v4
+  #         with:
+  #           node-version: 23.x
 
-      - name: Check if Yarn is installed
-        run: |
-          if ! command -v yarn &> /dev/null; then
-            echo "Yarn not found, installing..."
-            npm install -g yarn
-          else
-            echo "Yarn is already installed."
-          fi
+  #       - name: Check if Yarn is installed
+  #         run: |
+  #           if ! command -v yarn &> /dev/null; then
+  #             echo "Yarn not found, installing..."
+  #             npm install -g yarn
+  #           else
+  #             echo "Yarn is already installed."
+  #           fi
 
-      - name: Cache Yarn dependencies
-        uses: actions/cache@v2
-        with:
-          path: ~/.yarn/cache
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
+  #       - name: Cache Yarn dependencies
 
-      - name: Clean Install Dependencies
-        run: yarn install --check-files
+  #         uses: actions/cache@v2
+  #         with:
+  #           path: ~/.yarn/cache
+  #           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+  #           restore-keys: |
+  #             ${{ runner.os }}-yarn-
 
-      - name: Build the project
-        run: yarn build
+  #       - name: Clean Install Dependencies
+  #         run: yarn install --check-files
 
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-output
-          path: . # Adjust if build output is in a specific folder
+  #       - name: Build the project
+  #         run: yarn build
+
+  #       - name: Upload build artifacts
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           name: build-output
+  #           path: . # Adjust if build output is in a specific folder
 
   deploy:
     # needs: build
